version: '3'

services:
  checkoutce_db:
    image: mysql:5.7
    container_name: checkoutce_db
    restart: unless-stopped 
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SERVICE_TAGS: ${SERVICE_TAGS}
        SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - ce
  
  checkoutce_back:
    env_file:
      - api/.env
    build:
      context: api/
    networks:
      - ce
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - ./api/:/home/node/app
    depends_on:
      - checkoutce_db
    # command: bash -c 'npm install -g @loopback/cli && npm install && npm run rebuild && npm run start:watch'
    restart: on-failure

  checkoutce_front:
    env_file:
      - .env
    build:
      context: front/
    networks:
      - ce
    ports:
      - 8001:8001
    volumes:
      - ./front/:/home/node/app
    depends_on:
      - checkoutce_back
    # command: bash -c 'npm install && npm run start'
    restart: on-failure

networks:
  ce: